export const metadata = { title: "Privacy Policy — Mira" };

export default function Privacy() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-12 prose prose-neutral dark:prose-invert text-sm leading-6">
      <h1 className="text-2xl font-medium tracking-tight mb-2">Privacy Policy</h1>
      <p className="text-xs opacity-60 mb-6">Last updated: 2026-05-06</p>

      <h2 className="text-base font-medium mt-6 mb-2">Overview</h2>
      <p>
        Mira is a personal automation tool that runs locally on the account holder&apos;s machine.
        It connects to Instagram via the Instagram Business Login API to read and reply to
        comments and messages on the connected account.
      </p>

      <h2 className="text-base font-medium mt-6 mb-2">Data we collect</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li>Instagram access token (long-lived, stored locally on user&apos;s device)</li>
        <li>Public profile metadata (username, user ID) of the connected account</li>
        <li>Posts, captions, and comments accessible to the connected account</li>
        <li>Direct messages received by the connected account</li>
      </ul>

      <h2 className="text-base font-medium mt-6 mb-2">Where data is stored</h2>
      <p>
        All data is stored locally on the account holder&apos;s computer in the file
        <code className="mx-1">~/.mira/ig.json</code>. No data is transmitted to any third-party
        servers. No analytics, telemetry, or external storage is used.
      </p>

      <h2 className="text-base font-medium mt-6 mb-2">Use of data</h2>
      <p>
        Data is used solely to generate and send replies to comments and messages on behalf of
        the account holder. Replies are generated by a local large language model running on the
        same machine.
      </p>

      <h2 className="text-base font-medium mt-6 mb-2">Sharing</h2>
      <p>
        We do not share, sell, or transmit any data to third parties. The application makes
        outbound requests only to Instagram&apos;s public Graph API to fetch and post content on the
        connected account.
      </p>

      <h2 className="text-base font-medium mt-6 mb-2">Data retention &amp; deletion</h2>
      <p>
        All data lives only on the account holder&apos;s machine. To delete all data, disconnect the
        Instagram account in the app or remove the file <code>~/.mira/</code>.
      </p>

      <h2 className="text-base font-medium mt-6 mb-2">Contact</h2>
      <p>For questions: danyalforg@gmail.com</p>
    </main>
  );
}
