// Builds the self-contained Mira design bundle the WebView renders.
// Reads the editable design source + vendored runtime/logo from ./design,
// inlines everything (no relative refs, no network for assets), strips the
// phone-mockup chrome, and writes src/miraHtml.ts.
//
// Run from apps/mobile:  bun run build:design
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const design = join(root, 'design');

let out = readFileSync(join(design, 'Mira.dc.html'), 'utf8');
const support = readFileSync(join(design, 'support.js'), 'utf8');
const logoB64 = readFileSync(join(design, 'mira-logo-white.png')).toString('base64');

// inline support.js
out = out.replace('<script src="./support.js"></script>', `<script>\n${support}\n</script>`);
if (!out.includes('// GENERATED from dc-runtime')) throw new Error('support.js inline failed');

// inline logo (all occurrences)
const logoRefs = out.split('mira-logo-white.png').length - 1;
out = out.replaceAll('mira-logo-white.png', `data:image/png;base64,${logoB64}`);
if (logoRefs < 1) throw new Error('logo ref not found');

// strip phone-mockup chrome so the app fills the device (not phone-in-phone)
const fillCss = `
  html,body,#dc-root,#dc-root>.sc-host{height:100%;width:100%;background:var(--bg-frame);}
  #dc-root>.sc-host>div{min-height:0!important;height:100%!important;width:100%!important;padding:0!important;display:block!important;background:var(--bg-frame)!important;}
  [data-theme]{width:100%!important;height:100%!important;border-radius:0!important;padding:0!important;background:var(--bg-frame)!important;box-shadow:none!important;}
  [data-theme]>div:first-child{display:none!important;}
  [data-theme]>div:nth-child(2){border-radius:0!important;}
  [data-theme]>div:nth-child(2)>div:first-child{display:none!important;}
`;
out = out.replace('</helmet>', `<style>${fillCss}</style>\n</helmet>`);

// sanity: nothing left to fetch relatively
if (out.includes('"./support.js"') || out.includes('mira-logo-white.png'))
  throw new Error('relative refs remain');

const ts = `// AUTO-GENERATED by scripts/build-design.ts from design/Mira.dc.html — do not hand-edit.\nexport const miraHtml = ${JSON.stringify(out)};\n`;
writeFileSync(join(root, 'src', 'miraHtml.ts'), ts);
console.log(`built src/miraHtml.ts (${(ts.length / 1024).toFixed(0)} KB, logo refs: ${logoRefs})`);
